version: 2.1

orbs:
  sedstart: sedstart/cicd@dev:1

jobs:
   run-sedstart-local-windows:
    resource_class: 'windows.medium'
    machine:
      image: "windows-server-2022-gui:current"
      shell: "powershell.exe -ExecutionPolicy Bypass"
    steps:
      - checkout
      - sedstart/runlocal:
          api_key: SEDSTART_API_KEY
          project_id: 18
          test_id: 74
          profile_id: 36
          browser: "chrome"

workflows:
  test-workflow:
    jobs:
      - run-sedstart-local-windows
